name: Android Testing CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3 # preparar java
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest # ejecuta tests

      - name: Android Tests Report
        uses: asadmansr/android-test-report-action@v1.2.0 # reporte de los tests
        if: ${{ always() }} # ejecutar siempre, aunque los tests fallen